sudo: required
language: ruby
os:
  - linux
  - osx
rvm:
  - 2.2
services:
    - docker
    - postgresql
    - redis-server
before_install:
  - docker pull hello-world
  - docker run hello-world
  - bundle install
install:
  - wget djru.github.io
  - cat index.html
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
