sudo: required
dist: trusty
language: ruby
os:
  - linux
  - osx
rvm:
  - '2.2'
services:
    - docker
    - postgresql
    - redis-server
before_install:
  - docker pull hello-world
  - docker run hello-world
  - bundle install
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
install:
  - wget djru.github.io
  - cat index.html
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - redis-server
