sudo: required
language: ruby
dist: trusty
os:
  - linux
  - osx
rvm:
  - 2.2
services:
    - docker
before_install:
  - docker pull hello-world
  - docker run hello-world
install:
  - wget djru.github.io
  - cat index.html
